version: "3.8"

services:
  postgres:
    image: postgres
    restart: always
    env_file: ./.env
    environment:
      - POSTGRES_USER=${PRODUCTION_POSTGRES_USER}
      - POSTGRES_PASSWORD=${PRODUCTION_POSTGRES_PASSWORD}
      - POSTGRES_DB=${PRODUCTION_POSTGRES_DB}
    ports:
      - "${PRODUCTION_DB_PORT_EXPOSE}:${PRODUCTION_DB_PORT}"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spk-topsis
    ports:
      - "${PRODUCTION_PORT}:${PRODUCTION_PORT}"
    depends_on:
      - postgres
    env_file:
      - ./.env
    environment:
      - DB_HOST=postgres
      - DB_PORT=${PRODUCTION_DB_PORT}
      - DB_USER=${PRODUCTION_POSTGRES_USER}
      - DB_PASS=${PRODUCTION_POSTGRES_PASSWORD}
      - DB_NAME=${PRODUCTION_POSTGRES_DB}